//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "Contact")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Binary(16)")]
    pub id: Vec<u8>,
    pub name: String,
    #[sea_orm(column_type = "Binary(16)")]
    pub company_id: Vec<u8>,
    #[sea_orm(column_type = "Binary(16)")]
    pub user_id: Vec<u8>,
    #[sea_orm(column_type = "Binary(16)")]
    pub contact_type_id: Vec<u8>,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::contact_detail::Entity")]
    ContactDetail,
    #[sea_orm(
        belongs_to = "super::contact_type::Entity",
        from = "Column::ContactTypeId",
        to = "super::contact_type::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    ContactType,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UserId",
        to = "super::user::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    User,
}

impl Related<super::contact_detail::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContactDetail.def()
    }
}

impl Related<super::contact_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContactType.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
