@startuml name Double Entry System

actor User
' min 65 API '

package "Authentication" {
    ' routes auth '
    usecase register
    usecase login
    ' frontend handle, bec it stateless '
    usecase logout

    User --> (register)
    User --> (login)
    User --> (logout)
    ' 3 '
}

package "Account System Management" {
    
    ' routes user ' 
    usecase delete_account
    usecase update_user_profile
    usecase change_password
    usecase view_profile


    User --> (delete_account)
    User --> (update_user_profile)
    User --> (change_password)
    User --> (view_profile)
    ' 5 '
}

package "Company Management" {
    ' routes company '
    usecase create_company
    usecase edit_company
    usecase delete_company
    usecase view_company
    usecase view_companys
    

    User --> (create_company)
    User --> (edit_company)
    User --> (delete_company)
    User --> (add_user_to_company)
    User --> (remove_user_from_company)
    User --> (view_company)
    User --> (view_companys)
    User --> (view_company_users)
    ' 8 '

}

package "Customer Management" {
    ' customer '
    usecase create_customer
    usecase edit_customer
    usecase delete_customer
    usecase view_customer
    usecase view_customers
    
    ' contact '
    usecase create_customer_contact
    usecase edit_customer_contact
    usecase delete_customer_contact
    usecase view_customer_contact
    usecase view_customer_contacts
    
   
    
    User --> (create_customer)
    User --> (edit_customer)
    User --> (delete_customer)
    User --> (view_customer)
    User --> (view_customers)
    User --> (create_customer_contact)
    User --> (edit_customer_contact)
    User --> (delete_customer_contact)
    User --> (view_customer_contact)
    User --> (view_customer_contacts)
    ' 9 '
}

package "Project Management" {
    ' project '
    usecase create_project
    usecase edit_project
    usecase delete_project
    usecase view_project
    usecase view_projects
    
    ' location '
    usecase create_project_location
    usecase edit_project_location
    usecase delete_project_location
    usecase view_project_location

    ' location type '
    usecase create_location_type
    usecase edit_location_type
    usecase delete_location_type
    usecase view_location_type
    usecase view_location_types

    ' project_location'
    usecase attach_location_to_project
    usecase detach_location_from_project

    ' project info'
    usecase create_info
    usecase edit_info
    usecase update_info
    usecase delete_info
    usecase view_infos

    ' project status '
    usecase create_project_status
    usecase edit_project_status
    usecase delete_project_status
    usecase view_project_status
    usecase view_project_statuses



    User --> (create_project)
    User --> (edit_project)
    User --> (delete_project)
    User --> (view_project)
    User --> (view_projects)

    User --> (create_project_location)
    User --> (edit_project_location)
    User --> (delete_project_location)
    User --> (view_project_location)
    User --> (create_location_type)
    User --> (edit_location_type)
    User --> (delete_location_type)
    User --> (view_location_type)
    User --> (attach_location_to_project)
    User --> (detach_location_from_project)
    User --> (create_info)
    User --> (edit_info)
    User --> (delete_info)
    User --> (view_info)
    User --> (view_infos)
    User --> (create_project_status)
    User --> (edit_project_status)
    User --> (delete_project_status)
    User --> (view_project_status)
    User --> (view_project_statuses)
    ' 23 '

}

package "Account System Management" {
    usecase upload_chart_of_account_template
    usecase download_chart_of_account_template

    usecase create_chart_of_account
    usecase edit_chart_of_account
    usecase delete_chart_of_account
    usecase view_chart_of_account
    usecase view_chart_of_accounts

    usecase view_chart_of_account_balance
    usecase view_chart_of_account_transaction
    usecase view_chart_of_account_transactions

    usecase create_bank_account
    usecase edit_bank_account
    usecase delete_bank_account
    usecase view_bank_account
    usecase view_bank_accounts

    usecase create_bank_account_type
    usecase edit_bank_account_type
    usecase delete_bank_account_type
    usecase view_bank_account_type
    usecase view_bank_account_types

    usecase create_journal_entry
    usecase edit_jounal_entry
    usecase delete_journal_entry
    usecase view_journal_entry
    usecase view_journal_entrys

    User --> (upload_chart_of_account_template)
    User --> (download_chart_of_account_template)
    User --> (create_chart_of_account)
    User --> (edit_chart_of_account)
    User --> (delete_chart_of_account)
    User --> (view_chart_of_account)
    User --> (view_chart_of_accounts)
    
    User --> (view_chart_of_account_balance)
    User --> (view_chart_of_account_transaction)
    User --> (view_chart_of_account_transactions)

    User --> (create_bank_account)
    User --> (edit_bank_account)
    User --> (delete_bank_account)
    User --> (view_bank_account)
    User --> (view_bank_accounts)
    User --> (create_bank_account_type)
    User --> (edit_bank_account_type)
    User --> (delete_bank_account_type)
    User --> (view_bank_account_type)
    User --> (view_bank_account_types)
    User --> (create_journal_entry)
    User --> (edit_jounal_entry)
    User --> (delete_journal_entry)
    User --> (view_journal_entry)
    User --> (view_journal_entrys)
    ' 25 '
}
@enduml
