@startuml name Double Entry System

actor User
' min 62 API '

package "Authentication" {
    usecase Register
    usecase Login
    usecase Logout

    User --> (Register)
    User --> (Login)
    User --> (Logout)
    ' 3 '
}

package "User Management" {
    

    usecase ForgotPassword
    usecase DeleteAccount
    usecase ChangeEmail
    usecase ChangePassword
    usecase ViewProfile


    User --> (ForgotPassword)
    User --> (DeleteAccount)
    User --> (ChangeEmail)
    User --> (ChangePassword)
    User --> (ViewProfile)
    ' 5 '
}

package "Company Management" {
    
    usecase CreateCompany
    usecase EditCompany
    usecase DeleteCompany
    usecase AddUserToCompany
    usecase RemoveUserFromCompany
    usecase ViewCompany
    usecase ViewCompanies
    usecase ViewCompanyUsers

    User --> (CreateCompany)
    User --> (EditCompany)
    User --> (DeleteCompany)
    User --> (AddUserToCompany)
    User --> (RemoveUserFromCompany)
    User --> (ViewCompany)
    User --> (ViewCompanies)
    User --> (ViewCompanyUsers)
    ' 8 '

}

package "Customer Management" {
    
    usecase CreateCustomer
    usecase EditCustomer
    usecase DeleteCustomer
    usecase ViewCustomer
    usecase ViewCustomers
    usecase CreateCustomerContact
    usecase EditCustomerContact
    usecase DeleteCustomerContact
    usecase ViewCustomerContacts
    
    usecase LinkCustomerToCompany
    usecase UnlinkCustomerFromCompany
    usecase ManageCustomerStatus

    User --> (CreateCustomer)
    User --> (EditCustomer)
    User --> (DeleteCustomer)
    User --> (ViewCustomer)
    User --> (ViewCustomers)
    User --> (CreateCustomerContact)
    User --> (EditCustomerContact)
    User --> (DeleteCustomerContact)
    User --> (ViewCustomerContacts)
    ' 9 '
}

package "Project Management" {
    
    usecase CreateProject
    usecase EditProject
    usecase DeleteProject
    usecase ViewProject
    usecase ViewProjects
    
    usecase AttachProjectLocationToProject
    usecase DetachProjectLocationFromProject
    
    usecase CreateProjectLocation
    usecase EditProjectLocation
    usecase DeleteProjectLocation
    usecase ViewProjectLocations

    usecase CreateLocationType
    usecase EditLocationType
    usecase DeleteLocationType
    usecase ViewLocationTypes

    usecase CreateProjectInfo
    usecase EditProjectInfo
    usecase DeleteProjectInfo
    usecase ViewProjectInfo

    usecase CreateProjectStatus
    usecase EditProjectStatus
    usecase DeleteProjectStatus
    usecase ViewProjectStatus




    User --> (CreateProject)
    User --> (EditProject)
    User --> (DeleteProject)
    User --> (ViewProject)
    User --> (ViewProjects)
    User --> (AttachProjectLocationToProject)
    User --> (DetachProjectLocationFromProject)
    User --> (CreateProjectLocation)
    User --> (EditProjectLocation)
    User --> (DeleteProjectLocation)
    User --> (ViewProjectLocations)
    User --> (CreateLocationType)
    User --> (EditLocationType)
    User --> (DeleteLocationType)
    User --> (ViewLocationTypes)
    User --> (CreateProjectInfo)
    User --> (EditProjectInfo)
    User --> (DeleteProjectInfo)
    User --> (ViewProjectInfo)
    ' 19 '

}

package "Account System Management" {
    usecase UploadChartOfAccountTemplate
    usecase DownloadChartOfAccountTemplate
    usecase CreateChartOfAccount
    usecase EditChartOfAccount
    usecase DeleteChartOfAccount
    
    usecase ViewChartOfAccount
    usecase ViewChartOfAccountBalance
    usecase ViewChartOfAccountTransactions

    usecase CreateAccount
    usecase EditAccount
    usecase DeleteAccount
    usecase ViewAccount
    usecase ViewAccounts

    usecase CreateJournalEntry
    usecase EditJournalEntry
    usecase DeleteJournalEntry
    usecase ViewJournalEntry
    usecase ViewJournalEntries

    User --> (UploadChartOfAccountTemplate)
    User --> (DownloadChartOfAccountTemplate)
    User --> (CreateChartOfAccount)
    User --> (EditChartOfAccount)
    User --> (DeleteChartOfAccount)
    User --> (ViewChartOfAccount)
    User --> (ViewChartOfAccountBalance)
    User --> (ViewChartOfAccountTransactions)
    User --> (CreateAccount)
    User --> (EditAccount)
    User --> (DeleteAccount)
    User --> (ViewAccount)
    User --> (ViewAccounts)
    User --> (CreateJournalEntry)
    User --> (EditJournalEntry)
    User --> (DeleteJournalEntry)
    User --> (ViewJournalEntry)
    User --> (ViewJournalEntries)
    ' 18 '
}



@enduml





















User --> (Register)
User --> (Login)
User --> (Logout)
User --> (ForgotPassword)

User --> (View Profile)
User --> (Edit Profile)
User --> (Change Password)

User --> (Create Company)
User --> (Edit Company)
User --> (Delete Company)

User --> (Create Project)
User --> (Edit Project)
User --> (Delete Project)

User --> (Create Customer)
User --> (Edit Customer)
User --> (Delete Customer)

User --> (Create Product)
User --> (Edit Product)
User --> (Delete Product)

User --> (Create Expense)
User --> (Edit Expense)
User --> (Delete Expense)

User --> (Create Income)
User --> (Edit Income)
User --> (Delete Income)

User --> (Create Account)
User --> (Edit Account)
User --> (Delete Account)

User --> (Create Entry)
User --> (Edit Entry)
User --> (Delete Entry)

User --> (View Reports)
@enduml